<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array
     */
    protected $except = [
        //
    ];
    public function handle($request, Closure $next)
    {
        DB::connection()->enableQueryLog();
        $n =  parent::handle($request, $next); // TODO: Change the autogenerated stub
        $sql= DB::connection()->getQueryLog();
        DB::connection()->flushQueryLog();
        Log::info('sql',[$sql]);
        return $n;
    }
}
